extends Node
var super_dic1_texturas : Dictionary = {

	",cs2,suelo,mesh," : "suelo1",
	",cs2,pared1,mesh," : "suelo2",
	",cs2,pared2,mesh," : "suelo2",
	",cs2,pared3,mesh," : "suelo2",
	",cs2,pared4frag1,mesh," : "suelo2",
	",cs2,pared4frag2,mesh," : "suelo2",
	",cs2,pared4frag3,mesh," : "suelo2",
	",cs2,techo,mesh," : "techo_sala_2",
	",cs2,puente1,pared1" : "pared1",
	",cs2,puente1,pared2" : "pared1",
	",cs2,puente1,pared3" : "puente",
	",cs2,puente1," : "puente",
	
	",cs3,suelo,mesh," : "3suelo",
	",cs3,techo,mesh," : "3techo",
	",cs3,pared1,csgbox," : "3pared1",
	",cs3,pared2,csgbox," : "3pared2",
	",cs3,pared3,csgbox," : "3pared3",
	",cs3,frag_escalera_1,mesh," : "escalon1",
	",cs3,frag_escalera_2,mesh," : "escalon2",
	",cs3,pared4,csgbox," : "3pared4",
	#-----------------------------------------
	",cs3,puente2,mesh," : "puente23suelo",
	",cs3,puente3,mesh," : "puente23suelo",
	",cs3,puente4,mesh," : "puente4_suelo",
	",cs3,puente5,mesh," : "puente",
	#-----------------------------------------
	",cs3,puente2,pared1" : "pared3_sala4",
	",cs3,puente2,pared2" : "pared3_sala4",
	",cs3,puente2,pared3" : "techo_2",
	#-----------------------------------------
	",cs3,puente3,pared1" : "pared4_sala4",
	",cs3,puente3,pared2" : "pared4_sala4",
	",cs3,puente3,pared3" : "techo_1",
	#-----------------------------------------
	",cs3,puente4,pared1" : "pared5_sala5",
	",cs3,puente4,pared2" : "pared5_sala5",
	",cs3,puente4,pared3" : "puente4_techo",
	#-----------------------------------------
	",cs3,puente5,pared1" : "pared6_sala6",
	",cs3,puente5,pared2" : "pared6_sala6",
	",cs3,puente5,pared3" : "techo_1",
	
	",cs4,suelo,mesh," : "suelo_veneno",
	",cs4,techo,mesh," : "4techo",
	",cs4,pared1,csgbox," : "sala_4_1pared",
	",cs4,plataforma_lanzadera_1,mesh," : "plat_lanzadera_1",
	",cs4,pared2,csgbox," : "sala_4_2pared",
	",cs4,pared3,csgbox," : "sala_4_1pared",
	",cs4,plataforma_interruptor_1,mesh," : "plat_sagrada_1",
	",cs4,interruptor1,refc1_mesh," : "cilindro,sin,mas",
	",cs4,pared4,csgbox," : "sala_4_2pared",
	
	",cs5,suelo,csgbox," : "suelo_sala_5",
	",cs5,trap_node_1,mesh," : "suelo_trampilla",
	",cs5,trap_node_2,mesh," : "laterales_trampilla",
	",cs5,trap_node_3,mesh," : "laterales_trampilla",
	",cs5,trap_node_4,mesh," : "frontales_trampilla",
	",cs5,trap_node_5,mesh," : "frontales_trampilla",
	",cs5,interruptor1,refc1_mesh," : "cilindro,sin,mas",
	",cs5,techo,csgbox," : "techo_sala_5",
	",cs5,pared1,csgbox," : "pared_sala_5",
	",cs5,pared2,csgbox," : "pared_sala_5",
	",cs5,pared3,csgbox," : "pared_sala_5",
	",cs5,pared4,csgbox," : "pared_sala_5",
	
	",cs6,suelo,mesh," : "suelo_sala_6",
	",cs6,techo,mesh," : "techo_sala_6",
	",cs6,pared1,csgbox," : "pared1_sala_6",
	",cs6,pared2,csgbox," : "pared2_sala_6",
	",cs6,pared3,csgbox," : "pared3_sala_6",
	",cs6,plataforma_final_1,mesh," : "plat_lanzadera_2",
	",cs6,pared4,csgbox," : "pared4_sala_6",
	",cs6,cylinder1,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder2,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder3,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder4,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder5,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder6,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder7,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder8,cylinder,mesh," : "cilindro,sin,mas",
	",cs6,cylinder9,cylinder,mesh," : "cilindro,sin,mas",
	
}
